osx_image: xcode7.3
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS,Mac

script:
- xcodebuild clean build -project Gallery.xcodeproj -scheme Gallery-iOS -sdk iphonesimulator
- xcodebuild test -project Gallery.xcodeproj -scheme Gallery-iOS -sdk iphonesimulator
- xcodebuild clean build -project Gallery.xcodeproj -scheme Gallery-Mac -sdk macosx
- xcodebuild test -project Gallery.xcodeproj -scheme Gallery-Mac -sdk macosx
